### ISSUE TITLE
Add Djangos Messages Framework

### ISSUE THREAD

**Issue by rbialon** [Wegi/rpscene#18]
To display information to the user in an easy way, Djangos Messages Framework can be used.
Message display should be included in the `base.html` template and `django.contrib.messages` has to be added to `INSTALLED_APPS`.

**Comment by rbialon** [comment]
Okay, it's already included in `settings.py` :+1: 
So it only has to be included in the base template

**Comment by Wegi** [comment]
Merged, thanks :)
